[package]
name = "advent24"
version = "0.1.0"
edition = "2021"

[dependencies]
grid = "0.15.0"
itertools = "0.13.0"
lazy_static = "1.5.0"
once_cell = "1.20.2"
regex = "1.11.1"
rgb = "0.8.50"
textplots = "0.8.6"
